# permissions for end users to view example3s.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: example3-viewer-role
rules:
- apiGroups:
  - demo.fananchong.com
  resources:
  - example3s
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - demo.fananchong.com
  resources:
  - example3s/status
  verbs:
  - get
