# permissions for end users to view example2s.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: example2-viewer-role
rules:
- apiGroups:
  - demo.fananchong.com
  resources:
  - example2s
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - demo.fananchong.com
  resources:
  - example2s/status
  verbs:
  - get
